/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tomas' at '23.12.2016 14:22' with Gradle 3.2.1
 *
 * @author tomas, @date 23.12.2016 14:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
