import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tomas' at '23.12.2016 14:22' with Gradle 3.2.1
 *
 * @author tomas, @date 23.12.2016 14:22
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
